### PR TITLE
backport kernel-6.6-rc7

### PR DESCRIPTION
**Pull request by SergeyMy**

### CODE REVIEW

**Review by Fred78290 — CHANGES_REQUESTED** [review]
You missed to integrate the flag force.

```
else if (val == SIO_NCT6687_ID || val == SIO_NCT6687D_ID || force)
```

**Comment by SergeyMy** [comment]
Is it necessary to “forced” if available?
SIO_ID_MASK

**Comment by Fred78290** [comment]
> Is it necessary to “force” if available? SIO_ID_MASK

Yes it means that in last chance you can force to install the module without care chipset ID.
This was implemented by other authors to check if for unknown chipset the mod is fonctianaly.

You can add in the default case.

**Comment by SergeyMy** [comment]
ok added a bypass via force, although it is somewhat dangerous.

**Comment by Fred78290** [comment]
> ok added a bypass via force, although it is somewhat dangerous.

It's designed to test new chipset.

**Comment by jaythegreatman** [comment]
`#define` for chip ID 0xc732 and 0xd592 are deleted, but they remain in the description at the beginning of nct6687.c. Is this the intended behavior?

**Pull request merged**
